# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='owner',
            new_name='autor',
        ),
    ]
