# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('muro', '0004_auto_20160518_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=250, verbose_name='Text')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='texto',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Text'),
        ),
    ]
